services:
  db:
    image: mariadb:latest 
    container_name: mysql_pi
    restart: always
    environment:
      MYSQL_DATABASE: receptionist
      MYSQL_ROOT_PASSWORD: $3cret
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_pi
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db